### ISSUE TITLE
babel-preset-es2015-native-modules alternative module

### ISSUE THREAD

**Issue by bartekus** [gajus/babel-preset-es2015-webpack#1]
Babel != Webpack && Wepback != Babel
Should have checked with open babel 6 tickets about this, as there is already a es2015-native-modules registered on npm and on github 7 days earlier too... lol

https://www.npmjs.com/package/babel-preset-es2015-native-modules
https://github.com/Araphel/babel-preset-es2015-native-modules

**Comment by gajus** [comment]
Please use GitHub issue thread for reporting technical issues only. The use case of this module is documented in the project [`README.md`](https://github.com/gajus/babel-preset-es2015-webpack/blob/master/README.md) document. This issue appears to serve a solve purpose of advertising another project.

Thank you for referring me to the Babel issue thread. I have added a reference to this package (https://phabricator.babeljs.io/T3016#72546).

I see you have a similar module under development. Good luck with that.

**Comment by bartekus** [comment]
Sorry, didn't mean to be a pain but Webpack get's a lot of misdirected issues which are often cause by improper understanding and unfound expectations. 
We are working on minimizing these by properly highlighting what's what and which falls under who's jurisdiction. 
So on behalf of Webpack community thank you and have a nice day.

**Comment by gajus** [comment]
@Bartekus Would you rather I make you a collaborator of this project than maintaining two separate packages that do the same?

I understand if you choose not to, as you can position your package to a wider audience with a more generic name.

**Comment by bartekus** [comment]
Hey @gajus, Im not opposed to such idea as my only intention is to assist the community. 
We could technically provide both of them, since they are the same thing with a different name.

**Comment by gajus** [comment]
> in fact I've created araphel.org as sort of hackers for hackers community to keep package such as these under

What was the reason for creating a new community when there are several existing ones?

Those that come to my mind are:
- http://substack.net/
- https://h5bp.github.io/

There are a few more.

**Comment by bartekus** [comment]
We are in an essence organization of like-minded individuals and idealists who like to inspire and teach others yet our ideologies in general are based on esoteric and philosophical constructs.
