### ISSUE TITLE
Lockdown dependencies of `babel-preset-es2015` to stop it breaking people projects

### ISSUE THREAD

**Issue by andykenward** [gajus/babel-preset-es2015-webpack#14]
There are issues with the latest version of `babel-preset-es2015` `6.13.1` and this preset.

If you are having issue with this package in your project install

`npm i -D -E babel-preset-es2015@6.9.0` should solve it. (it did for me)

Can you please lockdown the version used in this preset. Should solve some headaches.
#12

**Comment by cklmercer** [comment]
Works for me! Thanks!

**Comment by zoontek** [comment]
The latest releases of `babel-core`and `babel-preset-2015` (6.13.2) now handle presets options! https://babeljs.io/docs/plugins/preset-es2015/ 🎉 

So instead of using this modified preset, you can now use:

```
// .babelrc
{
  "presets": [
    ["es2015", {"modules": false}]
  ]
}
```

**Comment by phairoh** [comment]
Thanks @zoontek, that seems to have fixed my problem. Just running `npm rm babel-preset-es2015-webpack` wasn't enough though, so I deleted my entire node_modules folder and that solved it.

**Comment by andykenward** [comment]
Using @zoontek solved the issue for me so can CLOSE #14 and stop using this preset.

**Comment by zwl1619** [comment]
@zoontek

where is `.babelrc` file ?

**Comment by nareshbhatia** [comment]
@zoontek, just to clarify, when using your solution the `es2015-webpack1` preset should be **replaced** by the `es2015` preset. Is this a correct assumptions? When I included both, the error reappears.

**Comment by zoontek** [comment]
The .babelrc file needs to be in the same folder as the package.json, and yes, should replace the `es2015-webpack` preset with the `es2015`.

**Comment by donaldpipowitch** [comment]
> So instead of using this modified preset, you can now use:
> 
> // .babelrc
> {
>   "presets": [
>     ["es2015", {"modules": false}]
>   ]
> }

Is it possible to do the same with query string syntax? E.g. `babel?presets[]=es2015...?`? 

I guess the best way is

```
`babel?${JSON.stringify({
  presets: [
    [ 'babel-preset-es2015' , { modules: false } ]
  ]
})}`
```
