### ISSUE TITLE
Why is there a travis badge with "passing" but there is not a single test?

### ISSUE THREAD

**Issue by MoOx** [gajus/babel-preset-es2015-webpack#5]
What is the point?

https://github.com/gajus/babel-preset-es2015-webpack/blob/420e47e4a2dc6caf2ab10aac63febc4ebdf4032e/package.json#L23

**Comment by MoOx** [comment]
(just curious)

**Comment by gajus** [comment]
Boilerplate.

**Comment by MoOx** [comment]
So do you activated travis on this repo from cli ? That would be interesting :)

**Comment by gajus** [comment]
It would be nice to have a test case, e.g. to check if versions of `babel-preset-es2015-webpack` dependencies match `babel-preset-es2015`. Unfortunately, there is no way to routinely run those tests on Travis, adding little benefit.

**Comment by gajus** [comment]
No, just routine. Open repo, activate travis, etc. I start every repo assuming it will be TDD. In this case, there simple wasn't anything to test.

**Comment by MoOx** [comment]
Ok thanks for the quick response.
